MSG_NOTIFY_DATA_BUFFER = "[S0NDB" # 
MSG_NO_NEW_UPDATE      = b"[S0NNU"
MSG_FILE_NOT_EXIST     = b"[S0FNE"
MSG_FILE_TRANSFER_END  = b"[S0FTE"
MSG_CLIENT_DISCONNECT  = b"[S0CDC"
MSG_SERVER_SIDE_CLOSE  = b"[S0SSC"

MSG_ASK_SERVER_TO_DIE  = b"[SOASD"